name: Pipeline

on:
  push:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup job
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./tests/coverage/
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Setup job
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: kong/setup-inso@v1
        with:
          inso-version: 3.5.0

      - name: Start database container
        run: docker-compose up --force-recreate -d postgres

      - name: Run migrations
        run: |
          echo "DATABASE_URL=postgresql://postgres:docker@localhost:5432/deliveryman?schema=public" > .env
          npx prisma migrate deploy

      - name: Set up environment variables
        env:
          JWT_CLIENT_SECRET: ${{ secrets.JWT_CLIENT_SECRET }}
          JWT_DELIVERYMAN_SECRET: ${{ secrets.JWT_DELIVERYMAN_SECRET }}
        run: |
          printf "PORT=3333\n\nJWT_CLIENT_SECRET=$JWT_CLIENT_SECRET\nJWT_DELIVERYMAN_SECRET=$JWT_DELIVERYMAN_SECRET\nJWT_EXPIRATION=1d\n\nDATABASE_URL="postgresql://postgres:docker@postgres:5432/deliveryman?schema=public"\n\nDOCS_URL=https://github.com/DiegoVictor/deliveryman#errors-reference" > .env

      - name: Run application container
        run: docker-compose up -d app

      - name: Check containers
        run: docker-compose ps -a

      - name: Run insomnia tests
        run: |
          sleep 10
          inso run test --src="Insomnia_2022-03-02.json" "Deliveryman" --env "UnitTest" --ci
