name: Pipeline

on:
  push:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup job
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./tests/coverage/
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: deliveryman
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Setup job
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: kong/setup-inso@v2
        with:
          inso-version: 10.3.1

      - name: Install dependecies
        run: npm ci

      - name: Run migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: postgresql://postgres:docker@localhost:5432/deliveryman?schema=public

      - name: Run application
        run: |
          npm run build
          node dist/src/shared/infra/http/server.js &
        env:
          JWT_CLIENT_SECRET: ${{ secrets.JWT_CLIENT_SECRET }}
          JWT_DELIVERYMAN_SECRET: ${{ secrets.JWT_DELIVERYMAN_SECRET }}
          PORT: 3333
          JWT_EXPIRATION: 1d
          DATABASE_URL: postgresql://postgres:docker@localhost:5432/deliveryman?schema=public
          DOCS_URL: https://github.com/DiegoVictor/deliveryman

      - name: Run insomnia tests
        run: |
          inso run test "Deliveryman" -w Insomnia_2024-12-15.json --env "Default" --ci
